###
POST http://localhost:8080/api/register
content-type: application/json

{
    "username": "dark",
    "password": "weider"
}
###
POST http://localhost:8080/api/login
content-type: application/json

{
     "username": "dark",
    "password": "weider"
}
###
GET http://localhost:8080/api/admin/user
###